"""add submission content and file_path

Revision ID: 8b8f0b20c37b
Revises: 
Create Date: 2025-12-31 09:58:20.272307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b8f0b20c37b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('homework_submissions', sa.Column('content', sa.Text(), nullable=True))
    op.add_column('homework_submissions', sa.Column('file_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('homework_submissions', 'file_path')
    op.drop_column('homework_submissions', 'content')
    # ### end Alembic commands ###
