"""add_saas_fields

Revision ID: 97185653efeb
Revises: 8b8f0b20c37b
Create Date: 2026-01-03 01:11:48.043270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97185653efeb'
down_revision: Union[str, Sequence[str], None] = '8b8f0b20c37b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parents_id'), 'parents', ['id'], unique=False)
    op.create_index(op.f('ix_parents_telegram_id'), 'parents', ['telegram_id'], unique=True)
    op.create_table('saas_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('provider_payment_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_payment_id')
    )
    op.create_index(op.f('ix_saas_payments_id'), 'saas_payments', ['id'], unique=False)
    op.create_table('parent_students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['parents.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_payments_id'), 'student_payments', ['id'], unique=False)
    op.add_column('students', sa.Column('balance', sa.Integer(), nullable=True))
    op.add_column('students', sa.Column('price_per_lesson', sa.Integer(), nullable=True))
    op.add_column('teachers', sa.Column('subscription_end_date', sa.DateTime(), nullable=True))
    op.add_column('teachers', sa.Column('subscription_plan', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teachers', 'subscription_plan')
    op.drop_column('teachers', 'subscription_end_date')
    op.drop_column('students', 'price_per_lesson')
    op.drop_column('students', 'balance')
    op.drop_index(op.f('ix_student_payments_id'), table_name='student_payments')
    op.drop_table('student_payments')
    op.drop_table('parent_students')
    op.drop_index(op.f('ix_saas_payments_id'), table_name='saas_payments')
    op.drop_table('saas_payments')
    op.drop_index(op.f('ix_parents_telegram_id'), table_name='parents')
    op.drop_index(op.f('ix_parents_id'), table_name='parents')
    op.drop_table('parents')
    # ### end Alembic commands ###
