"""fix student payments structure

Revision ID: e5badf363af6
Revises: 97185653efeb
Create Date: 2026-01-03 01:44:01.322846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5badf363af6'
down_revision: Union[str, Sequence[str], None] = '97185653efeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_payments', sa.Column('teacher_id', sa.Integer(), nullable=False))
    op.add_column('student_payments', sa.Column('lessons_added', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'student_payments', 'teachers', ['teacher_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student_payments', type_='foreignkey')
    op.drop_column('student_payments', 'lessons_added')
    op.drop_column('student_payments', 'teacher_id')
    # ### end Alembic commands ###
